### ISSUE TITLE
Omit function return type if function returns void

### ISSUE THREAD

**Issue by BrixsterPlanet** [Polytoria/Docs#104]
Since Lua isn't a typed language it's pretty unnecessary for all of these functions to have this " -> `void` " nonsense if they don't have a return value

This is a personal chore for me to do later but if anyone else wants to tackle it i'm fine with that. Should be a simple change in the python templater

**Comment by indexxing** [comment]
that may have been me sorry lol ill fix that right now

**Comment by indexxing** [comment]
#105
