### ISSUE TITLE
Spotlight

### ISSUE THREAD

**Issue by IndexingGitHub** [Polytoria/Docs#40]
Wrong documentation

**Comment by BrixsterPlanet** [comment]
Please elaborate

**Comment by IndexingGitHub** [comment]
Don't tell me what to do (just kidding!). Anyways. For one, **the name in the text is the wrong name it says PointLight in the description for Spotlight**. And for two, I'm not entirely sure if the description is correct at all (it seems to be after further reviewing like your tag says this issue needs)

This wasn't a pull request because I originally thought that the description was completely wrong, but it isn't, I think. So, I made it an issue on my phone and didn't feel like writing so that's why it's straight to the point and simple.
