### ISSUE TITLE
Undocumented input methods

### ISSUE THREAD

**Issue by willemsteller** [Polytoria/Docs#61]
Vector3 GetMouseWorldPosition()
Vector3 GetMouseWorldPoint()
RayResult ScreenPointToRay(Vector3 pos, List<Instance> ignoreList = null)
RayResult ViewportPointToRay(Vector3 pos, List<Instance> ignoreList = null)

**Comment by StarManTheGamer** [comment]
Can you tell me which are methods, properties, etc so i can properly sort them

**Comment by indexxing** [comment]
> Can you tell me which are methods, properties, etc so i can properly sort them

The issue is literally called "Undocumented methods"...
