### ISSUE TITLE
RemoteEvent icon is missing on removed classes page

### ISSUE THREAD

**Issue by Arexvy** [Polytoria/Docs#92]
![chrome_8aIy9OQNKx](https://github.com/Polytoria/Docs/assets/145375423/6f724d27-ae8c-457f-96f4-d156c05656e5)

https://docs.polytoria.com/removed/

**Comment by indexxing** [comment]
No icon made for that, probably could just use NetworkEvent icon.
I made that page lol I think I forgot about that or just ignored it

**Comment by Alyxsqrd** [comment]
Fixed in #96
